- name: Understanding variables
  hosts: all
  become: yes
  tasks:
    - name: create user
      ansible.builtin.user:
        name: "{{username}}"
        comment: "{{comment}}"
      register: user_out

    - debug:
        var: user_out.name
    
    - debug:
        var: user_out.comment