---
- name: Provisioning Servers
  hosts: all
  become: yes
  tasks:
    - name: Install ntp agent on CentOS 
      yum: 
        name: chrony 
        state: present
      when: ansible_distribution == "CentOS"
    
    - name: Install ntp agent on ubuntu
      apt:
        name: ntp
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Start the service on CentOS 
      service: 
        name: chronyd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"

    - name: Start the service on Ubuntu 
      service: 
        name: ntp
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"



